general {
    col.active_border = rgb(C0C0C0) rgb(D3D3D3) rgb(E5E5E5) rgb(B0B0B0)
    
    gaps_in = 2
    gaps_out = 6
    border_size = 1

}

# Window Style
decoration {
    # orig
    rounding = 5
    dim_inactive = true
    dim_strength = 0.15 

    active_opacity = 0.8
    inactive_opacity = 0.70

    shadow {
        enabled = true
        color = rgba(0, 0, 0, 1)
        range = 1
        render_power = 1
    color = rgba(167, 167, 167, 0.8)
    }
# ✅ Blur (new syntax)
    blur {
        enabled = true
        size = 4
        passes = 3
        contrast = 1.0
        brightness = 0.9
        vibrancy = 0.1
        noise = 0.01
        ignore_opacity = false
        new_optimizations = on
    }
}  
    animations {
    enabled = true
    bezier = mycurve, 0.1, 0.9, 0.2, 1.0
    animation = windows, 1, 6, mycurve, popin
    animation = border, 1, 5, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, default, slide
    }


layerrule {
    name = blur_with_ignore_alpha
    match:namespace = ^(walker|notifications|swayosd|waybar)$
    blur = true
    ignore_alpha = 0.1
}
